[package]
name = "ipsj-template"
version = "0.0.0"
entrypoint = "lib.typ"
authors = ["mkpoli <mkpoli@mkpo.li>"]
license = "MIT"
description = "IPSJ Technial Report template"

[template]
entrypoint = "main.typ"
