[package]
name = "ipsj-template"
version = "0.0.0"
entrypoint = "lib.typ"
repository = "https://github.com/mkpoli/ipsj-typst-template"
authors = ["mkpoli <mkpoli@mkpo.li>"]
license = "MIT"
description = "IPSJ Technial Report template"
keywords = [
    "Information Processing Society of Japan",
    "IPSJ",
    "japanese",
    "Computer Science",
    "Computer Engineering",
    "Software",
    "Digital Humanities",
]
categories = ["paper", "report"]

[template]
entrypoint = "main.typ"
path = "template"
thumbnail = "thumbnail.png"
